import { compileProgram, EndpointProgramPlayer, ProgramTimeline, CheckoutEngine, ReconciliationEngine, EntitlementLedger } from '@neophilism/distributed-audio-engine';
import type { CiphertextChunkTransport } from '@neophilism/distributed-audio-engine';
import { SqliteCheckpointStore, SqliteEntitlementStore } from '@neophilism/distributed-audio-engine/node';
import { OutputEvidenceEndpoint } from '@neophilism/distributed-audio-engine/evidence';
import { OutputLifecycle } from '@neophilism/distributed-audio-engine/output-lifecycle';
import { AndroidAudioSink } from '@neophilism/distributed-audio-engine/android';
import { IOSAudioSink } from '@neophilism/distributed-audio-engine/ios';
const timeline = new ProgramTimeline(0, compileProgram('program', 8000, [{ id: 'clip', assetId: 'asset', frames: 8000, markerAfter: null }]));
declare const transport: CiphertextChunkTransport;
void [timeline, transport, EndpointProgramPlayer, SqliteCheckpointStore, SqliteEntitlementStore, CheckoutEngine, ReconciliationEngine, EntitlementLedger, OutputEvidenceEndpoint, OutputLifecycle, AndroidAudioSink, IOSAudioSink];
